Release 10.39.02
git-svn-id: http://svn.code.sf.net/p/netpbm/code/advanced@360 9d0c8265-081b-0410-96cb-a4ca84ce46f8

diff --git a/editor/pamstretch-gen b/editor/pamstretch-gen
--- a/editor/pamstretch-gen
+++ b/editor/pamstretch-gen
@@ -32,11 +32,11 @@ if [ "$1" = "" ]; then
 fi
 
 tempdir="${TMPDIR-/tmp}/pamstretch-gen.$$"
-mkdir $tempdir || { echo "Could not create temporary file. Exiting."; exit 1;}
-chmod 700 $tempdir
-tempfile=$tempdir/pnmig
-
+mkdir -m 0700 $tempdir || \
+  { echo "Could not create temporary file. Exiting."; exit 1;}
 trap 'rm -rf $tempdir' 0 1 3 15
+
+tempfile=$tempdir/pnmig
 
 if ! cat $2 >$tempfile 2>/dev/null; then
   echo 'pamstretch-gen: error reading file' 1>&2
