Release 10.40.00
git-svn-id: http://svn.code.sf.net/p/netpbm/code/release_number/10.40.0@415 9d0c8265-081b-0410-96cb-a4ca84ce46f8

diff --git a/editor/pnmmargin b/editor/pnmmargin
--- a/editor/pnmmargin
+++ b/editor/pnmmargin
@@ -12,9 +12,8 @@
 # implied warranty.
 
 tempdir="${TMPDIR-/tmp}/pnmmargin.$$"
-mkdir $tempdir || { echo "Could not create temporary file. Exiting."; exit 1;}
-chmod 700 $tempdir
-
+mkdir -m 0700 $tempdir || \
+  { echo "Could not create temporary file. Exiting."; exit 1;}
 trap 'rm -rf $tempdir' 0 1 3 15
 
 tmp1=$tempdir/pnmm1
@@ -23,19 +22,24 @@ tmp3=$tempdir/pnmm3
 tmp4=$tempdir/pnmm4
 
 color="-gofigure"
+plainopt=""
 
 # Parse args.
 while true ; do
     case "$1" in
-	-w* )
+        -p|-pl|-pla|-plai|-plain )
+        plainopt="-plain"
+        shift
+        ;;
+	-w|-wh|-whi|-whit|-white )
 	color="-white"
 	shift
 	;;
-	-b* )
+	-b|-bl|-bla|-blac|-black )
 	color="-black"
 	shift
 	;;
-	-c* )
+	-c|-co|-col|-colo|-color )
 	shift
 	if [ ! ${1-""} ] ; then
 	    echo "usage: $0 [-white|-black|-color <colorspec>] <size> [pnmfile]" 1>&2
@@ -85,4 +89,5 @@ pamflip -rotate90 $tmp2 > $tmp3
 
 # Cat things together.
 pnmcat -lr $tmp2 $tmp1 $tmp2 > $tmp4
-pnmcat -tb $tmp3 $tmp4 $tmp3
+pnmcat -tb $plainopt $tmp3 $tmp4 $tmp3
+
