Fix handling of mktemp failure
git-svn-id: http://svn.code.sf.net/p/netpbm/code/trunk@3871 9d0c8265-081b-0410-96cb-a4ca84ce46f8

diff --git a/converter/ppm/hpcdtoppm/pcdovtoppm b/converter/ppm/hpcdtoppm/pcdovtoppm
--- a/converter/ppm/hpcdtoppm/pcdovtoppm
+++ b/converter/ppm/hpcdtoppm/pcdovtoppm
@@ -113,7 +113,7 @@ if [ $# = 0 ]; then
 fi
 
 tempdir=$(mktemp -d "${TMPDIR:-/tmp}/pcdovtoppm.XXXXXXXX") ||
-    ( echo "Could not create temporary file. Exiting." 1>&2; exit 1; ) 
+    { echo "Could not create temporary file. Exiting." 1>&2; exit 1; }
 trap 'rm -rf $tempdir' 0
 
 tmpfile=`tempfile -p pi -m 600`
