improve syntax error messages
git-svn-id: http://svn.code.sf.net/p/netpbm/code/trunk@5033 9d0c8265-081b-0410-96cb-a4ca84ce46f8

diff --git a/converter/ppm/hpcdtoppm/pcdovtoppm b/converter/ppm/hpcdtoppm/pcdovtoppm
--- a/converter/ppm/hpcdtoppm/pcdovtoppm
+++ b/converter/ppm/hpcdtoppm/pcdovtoppm
@@ -30,31 +30,16 @@ plainopt=""       # output plain ppm
 quietopt=""       # quiet operation (currently no effect)
 versionopt=0
 
-usage ()
+syntaxError ()
 {
-    echo "Usage: $0 [-m W] [-s S] [-a A] [-c N|n] [-f F] [-b|-w] <overview.pcd>"
-    echo " with"
-    echo "      W = maximum width of the result image   (default: $maxwidth)"
-    echo "      S = maximum size of each of the images  (default: $size)"
-    echo "      A = maximum number of images across     (default: $across)"
-    echo "      N = maximum number of colors or noquant (default: $colors)"
-    echo -n "   F = font to be used for annotation      (default: "
-    if [ "$font" = " " ] ; then
-                echo "internal font)"
-    else
-                echo "$font)"
-    fi
-    echo "      -b/-w = black/white background color    (default: $back)"
-    echo " "
-    echo " e.g.: $0 -m 768 -s 96 -f smallfont.pbm overview.pcd > overview.ppm"
-    echo " or  : $0 /cdrom/photo_cd/overview.pcd | ppmtojpeg > overview.jpg"
-    exit 1
+    echo "Syntax error: $1" 1>&2
+    exit 5
 }
 
 version ()
 {
-    # report version using pnmscale
-    pnmscale -version $quietopt
+    # report version using pamscale
+    pamscale -version $quietopt
     exit 0
 }
 
@@ -62,35 +47,45 @@ version ()
 while :; do
     case "$1" in 
         -m|-ma|-max|-maxw|-maxwi|-maxwid|-maxwidt|-maxwidth )
-             if [ $# -lt 2 ] ; then usage; fi
-             maxwidth="$2"
-             shift
-             shift
-             ;;
+            if [ $# -lt 2 ] ; then
+                syntaxError "-maxwidth requires an argument"
+            fi
+            maxwidth="$2"
+            shift
+            shift
+            ;;
 
         -s|-si|-siz|-size )
-             if [ $# -lt 2 ] ; then usage; fi
+            if [ $# -lt 2 ] ; then
+                syntaxError "-size requires an argument"
+            fi
              size="$2"
              shift
              shift
              ;;
 
          -a|-ac|-acr|-acro|-acros|-across )
-             if [ $# -lt 2 ] ; then usage; fi
+             if [ $# -lt 2 ] ; then
+                 syntaxError "-across requires an argument"
+             fi
              across="$2"
              shift
              shift
              ;;
 
          -c|-co|-col|-colo|-color|-colors )
-             if [ $# -lt 2 ] ; then usage; fi
+             if [ $# -lt 2 ] ; then
+                 syntaxError "-colors requires an argument"
+             fi
              colors="$2"
              shift
              shift
              ;;
 
          -f|-fo|-fon|-font )
-             if [ $# -lt 2 ] ; then usage; fi
+             if [ $# -lt 2 ] ; then
+                 syntaxError "-font requires an argument"
+             fi
              font="-font $2"
              shift
              shift
@@ -122,9 +117,7 @@ while :; do
              ;;
                     
          -*)
-             echo "$0 : Unknown option $1" 1>&2
-             echo " " 1>&2
-             usage
+             syntaxError "$0 : Unknown option $1"
              ;;
 
          *)
@@ -136,8 +129,6 @@ done
 
 if [ $versionopt -eq 1 ] ; then
     version
-elif [ $# -eq 0 ] ; then
-    usage
 fi
 
 tempdir=$(mktemp -d "${TMPDIR:-/tmp}/pcdovtoppm.XXXXXXXX") ||
